# Numpy

In Linear Algebra there are two types of data:
1. Scalar: e.g. 3
2. Vector: e.g. [3, 5, 6, 7]

In [2]:
import numpy as np
arr1 = np.arange(10)
arr2 = np.arange(10) * 10
arr3 = arr1 + arr2
print (arr3)

[ 0 11 22 33 44 55 66 77 88 99]


## Why Numpy?
Numpy is faster than normal Python's list.
Let us see how we measure that:

In [3]:
import sys
from datetime import datetime
def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

def pysum(n):
    a = range(n)
    b = range(n)
    c = [i ** 2 + i ** 3 for i in range(n)]
    return c

test_number = 10000
start = datetime.now()
c = pysum(test_number)
delta = datetime.now() - start

print ('python elapsed time in ms: ', delta.microseconds)

start = datetime.now()
c = numpysum(test_number)
delta = datetime.now() - start

print ('numpy elapsed time in ms: ', delta.microseconds)

python elapsed time in ms:  8207
numpy elapsed time in ms:  640


====================================================================================================================

## types and dimensions:

In [4]:
a = np.arange(10)
print (a.dtype)
print (a.shape)

int64
(10,)


In [7]:
print ("In: arange(7, dtype=uint16)")
print (np.arange(7, dtype=np.uint16))

In: arange(7, dtype=uint16)
[0 1 2 3 4 5 6]


In [8]:
np.dtype(float)

dtype('float64')

In [9]:
dt = np.dtype(np.complex128)
dt.type

numpy.complex128

### multi-dimentional array:

In [6]:
a = np.array([np.arange(4), np.arange(4)])
print(a)
a.shape

[[0 1 2 3]
 [0 1 2 3]]


(2, 4)